spring:
  application:
   name: blog

  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/self_home
    username: root
    password: 123456



server:
  port: 8123
  servlet:
    context-path: /api


# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.seeback.blog.controller

storage:
  smms:
    base-url: https://smms.app/api/v2
    token: ${SMMS_TOKEN:}
    max-size: 5242880
    allowed-types: image/jpeg,image/png,image/webp,image/gif

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn



